apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-server.fullname" . }}
  labels:
    {{- include "grpc-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.sidecar.port }}
      targetPort: http-envoy
      protocol: TCP
      name: http-envoy
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "grpc-server.selectorLabels" . | nindent 4 }}
